<a href="https://colab.research.google.com/github/elangbijak4/LLM-SLM-Examples/blob/main/Hitung_Bobot_WQ_WK_WV_Layer_Enkoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Fungsi untuk membuat matriks bobot secara acak
def create_weight_matrix(input_size, output_size):
    return tf.Variable(tf.random.normal([input_size, output_size], stddev=0.1))

# Fungsi untuk melakukan operasi linear
def linear(inputs, weight_matrix):
    return tf.matmul(inputs, weight_matrix)

# Contoh data input (token embedding)
token_embedding = tf.constant([[0.1, 0.2, 0.3, 0.4], [0.5, 0.6, 0.7, 0.8]])

# Menciptakan matriks bobot untuk Q, K, dan V secara acak
hidden_size = 4
num_heads = 2
WQ = create_weight_matrix(hidden_size, hidden_size)
WK = create_weight_matrix(hidden_size, hidden_size)
WV = create_weight_matrix(hidden_size, hidden_size)

# Operasi linear untuk menghasilkan Q, K, dan V
Q = linear(token_embedding, WQ)
K = linear(token_embedding, WK)
V = linear(token_embedding, WV)

print("Matriks bobot Q:")
print(WQ)
print("\nMatriks bobot K:")
print(WK)
print("\nMatriks bobot V:")
print(WV)

Matriks bobot Q:
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.05439621, -0.10820009, -0.12972192,  0.18169491],
       [ 0.12179729, -0.05613254, -0.16733696,  0.19259092],
       [ 0.08902131, -0.003108  ,  0.01908132,  0.04266546],
       [ 0.06633249,  0.01292526, -0.0542859 , -0.03280606]],
      dtype=float32)>

Matriks bobot K:
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.05142703, -0.03525243, -0.04482372,  0.13129558],
       [ 0.10648432,  0.01935928, -0.11253174,  0.17875813],
       [-0.00074239, -0.03765871,  0.07156657,  0.10010278],
       [-0.02935515, -0.15970357,  0.1275543 , -0.01814561]],
      dtype=float32)>

Matriks bobot V:
<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.1073515 , -0.11238644, -0.04823754,  0.04739756],
       [-0.01839872, -0.02265745,  0.03653766, -0.05909519],
       [ 0.11846621,  0.00170654, -0.0942215 ,  0.02728173],
       [ 0.0178106 ,  0.054965  ,  0.22610863, 